
{{- if .Values.pipeline.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: job-pipelinerun-upload-{{ .Values.pipeline.name }}
  namespace: {{ $.Values.project.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  template:
    spec:
      containers:
      - name: pipelinerun
        image: registry.redhat.io/openshift4/ose-tools-rhel8:v4.14
        imagePullPolicy: IfNotPresent        
        command: ["/bin/bash"]
        args:
        - -ec
        - |-
          # Define the namespace and label
          NAMESPACE="{{ $.Values.project.name }}"
          LABEL="initial=true"

          # Check if there is a pod with the specified label in the specified namespace
          if ! oc get pods -n "$NAMESPACE" -l "$LABEL" --no-headers | grep -q '^'; then
              tkn pipeline start pipeline-upload-{{ .Values.pipeline.name }} -l initial=true --workspace name=workspace-source,claimName=pipeline-upload-{{ .Values.pipeline.name }}-source-pvc -n $namespace --showlog --use-param-defaults
              sleep 10
              tkn pipeline start pipeline-run-{{ .Values.pipeline.name }} -l initial=true -n $namespace --showlog
          fi
      restartPolicy: Never
  backoffLimit: 1
{{- end }}

