{{ range $notebook := $.Values.notebooks }}
{{- if $notebook.enabled }}
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    openshift.io/display-name: {{ $notebook.name }}-inference
    serving.knative.openshift.io/enablePassthrough: 'true'
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
    #serving.kserve.io/storage-initializer-uid: "1000970001" # https://github.com/kserve/kserve/blob/master/docs/OPENSHIFT_GUIDE.md#with-service-mesh-istio
  name: {{ $notebook.name }}-inference
  namespace: {{ $.Values.project.name }}
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: onnx
        version: '1'
      resources:
        limits:
          cpu: '2'
          memory: 8Gi
        requests:
          cpu: '1'
          memory: 4Gi
      runtime: {{ $notebook.name }}-inference-runtime
      storage:
        key:  {{ $notebook.inferencedataconnections }}
        path: models/{{ $notebook.name }}/1/model.onnx  #TODO play with model versions
{{- end }}
{{- end }}
