{{ range .Values.dataconnections }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.project.name }}
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: {{ .name }}
stringData:
  AWS_ACCESS_KEY_ID: {{ .data.AWS_ACCESS_KEY_ID }}
  AWS_DEFAULT_REGION: {{ .data.AWS_DEFAULT_REGION }}
  AWS_S3_BUCKET: {{ .data.AWS_S3_BUCKET }}
  AWS_S3_ENDPOINT: {{ printf "%s://%s" .data.scheme .data.AWS_S3_ENDPOINT }}
  AWS_SECRET_ACCESS_KEY: {{ .data.AWS_SECRET_ACCESS_KEY }}
type: Opaque
{{ end }}

{{ if $.Values.pipeline.enabled }}
{{ with .Values.pipeline }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.project.name }}
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: {{ .name }}
stringData:
  AWS_ACCESS_KEY_ID: {{ .dataconnection.data.AWS_ACCESS_KEY_ID }}
  AWS_DEFAULT_REGION: {{ .dataconnection.data.AWS_DEFAULT_REGION }}
  AWS_S3_BUCKET: {{ .dataconnection.data.AWS_S3_BUCKET }}
  AWS_S3_ENDPOINT: {{ printf "%s://%s" .dataconnection.data.scheme .dataconnection.data.AWS_S3_ENDPOINT }}
  AWS_SECRET_ACCESS_KEY: {{ .dataconnection.data.AWS_SECRET_ACCESS_KEY }}
type: Opaque
{{ end }}
{{ end }}


