apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-fraud-example-mult
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: default
  source: 
    path: ai-examples/charts/onboard-datascience
    repoURL: 'https://github.com/davidseve/mlops.git'
    targetRevision: HEAD
    helm:
      valueFiles:
      - ../../fraud-detection/gitops/mult/values-fraud-mult.yaml  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true